/*
 * Copyright (C) 2023 Yaraku, Inc.
 *
 * This file is part of Human Evaluation Tool.
 *
 * Human Evaluation Tool is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Human Evaluation Tool is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Human Evaluation Tool. If not, see <https://www.gnu.org/licenses/>.
 *
 * AUTO-GENERATED by scripts/gen_categories.py — edit config/categories.txt instead.
 */

export default function ErrorCategorySelector(props) {
  return (
    <select
      className={props.className}
      disabled={props.disabled}
      onChange={props.onChange}
      value={props.value}
    >
      <optgroup>
        <option id="000" value="000">
          No Error
        </option>
      </optgroup>
      <optgroup label="Accuracy">
        <option id="A01" value="A01">
          Mistranslation
        </option>
        <option id="A02" value="A02">
          Overtranslation
        </option>
        <option id="A03" value="A03">
          Undertranslation
        </option>
        <option id="A04" value="A04">
          Omission
        </option>
        <option id="A05" value="A05">
          Addition
        </option>
        <option id="A06" value="A06">
          Transposition
        </option>
        <option id="A07" value="A07">
          Untranslated
        </option>
        <option id="A08" value="A08">
          Gibberish
        </option>
        <option id="A09" value="A09">
          Other
        </option>
      </optgroup>
      <optgroup label="Linguist conventions">
        <option id="L01" value="L01">
          Grammar and syntax
        </option>
        <option id="L02" value="L02">
          Punctuation
        </option>
        <option id="L03" value="L03">
          Spelling
        </option>
        <option id="L04" value="L04">
          Character
        </option>
        <option id="L05" value="L05">
          Others
        </option>
      </optgroup>
      <optgroup label="Terminology">
        <option id="T01" value="T01">
          Inconsistent with terminology resources
        </option>
        <option id="T02" value="T02">
          Wrong term
        </option>
        <option id="T03" value="T03">
          Inconsistent use
        </option>
        <option id="T04" value="T04">
          Other
        </option>
      </optgroup>
      <optgroup label="Style">
        <option id="S01" value="S01">
          Textual conventions
        </option>
        <option id="S02" value="S02">
          Register
        </option>
        <option id="S03" value="S03">
          Lack of clarity
        </option>
        <option id="S04" value="S04">
          Conciseness
        </option>
        <option id="S05" value="S05">
          Unidiomatic
        </option>
        <option id="S06" value="S06">
          Coherence and cohesion
        </option>
        <option id="S07" value="S07">
          Inconsistent with external reference
        </option>
        <option id="S08" value="S08">
          Others
        </option>
      </optgroup>
      <optgroup label="Locale">
        <option id="LC1" value="LC1">
          Locale convention
        </option>
      </optgroup>
      <optgroup label="Audience appropriateness">
        <option id="P01" value="P01">
          Culture-specific reference
        </option>
        <option id="P02" value="P02">
          Offensive
        </option>
        <option id="P03" value="P03">
          Other
        </option>
      </optgroup>
      <optgroup label="SourceError">
        <option id="SE1" value="SE1">
          Source Error
        </option>
      </optgroup>
    </select>
  );
}
